server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: smart-waste-management
  
  datasource:
    url: jdbc:mysql://localhost:3306/waste_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Anavatti@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload-dir: uploads/

# Logging
logging:
  level:
    com.wastemanagement: DEBUG
    org.springframework.security: DEBUG